"use client";
import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatDate } from "@/lib/utils";
import { INCIDENT_TYPE_LABELS } from "@/lib/types";
import { toast } from "sonner";

interface Props {
  incident: {
    id: string;
    participant_first_name: string;
    incident_date: string;
    incident_time: string;
    location: string;
    incident_type: string;
    description: string;
    immediate_action: string;
    reported_to_ndis: boolean;
    ndis_report_date: string | null;
    created_at: string;
  };
  profile: {
    business_name: string | null;
    contact_name: string | null;
  } | null;
}

export function IncidentPDFDownload({ incident, profile }: Props) {
  async function handleDownload() {
    try {
      const { default: jsPDF } = await import("jspdf");
      const doc = new jsPDF({ format: "a4", unit: "mm" });
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const maxWidth = pageWidth - margin * 2;
      let y = 20;

      // Header
      doc.setFillColor(30, 58, 95);
      doc.rect(0, 0, pageWidth, 40, "F");
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(255, 255, 255);
      doc.text("NDIS Incident Report", margin, 20);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(profile?.business_name || "NDIS Provider", margin, 30);
      doc.text(`Ref: ${incident.id.slice(0, 8).toUpperCase()}`, pageWidth - margin, 30, { align: "right" });
      y = 55;

      function addSection(title: string, content: string) {
        if (y > 250) { doc.addPage(); y = 20; }
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(30, 58, 95);
        doc.text(title, margin, y);
        y += 1;
        doc.setDrawColor(30, 58, 95);
        doc.setLineWidth(0.3);
        doc.line(margin, y, pageWidth - margin, y);
        y += 5;
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(15, 23, 42);
        const lines = doc.splitTextToSize(content, maxWidth);
        if (y + lines.length * 6 > 270) { doc.addPage(); y = 20; }
        doc.text(lines, margin, y);
        y += lines.length * 6 + 8;
      }

      addSection("Provider Details", `Business: ${profile?.business_name || "N/A"}\nContact: ${profile?.contact_name || "N/A"}\nReport Date: ${formatDate(incident.created_at)}`);
      addSection("Incident Summary", `Participant (First Name Only): ${incident.participant_first_name}\nType: ${INCIDENT_TYPE_LABELS[incident.incident_type as keyof typeof INCIDENT_TYPE_LABELS] || incident.incident_type}\nDate: ${formatDate(incident.incident_date)}\nTime: ${incident.incident_time.slice(0, 5)}\nLocation: ${incident.location}`);
      addSection("Description of Incident", incident.description);
      addSection("Immediate Action Taken", incident.immediate_action);
      addSection("NDIS Commission Reporting", incident.reported_to_ndis ? `Status: Reported to NDIS Commission\nDate Reported: ${incident.ndis_report_date ? formatDate(incident.ndis_report_date) : "Not specified"}` : "Status: Not yet reported to NDIS Commission\nNote: Review reporting obligations under Section 73Z of the NDIS Act 2013.");

      // Signature block
      if (y > 240) { doc.addPage(); y = 20; }
      y += 10;
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, y, margin + 70, y);
      doc.line(margin + 90, y, margin + 160, y);
      y += 5;
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.text("Signature", margin, y);
      doc.text("Date", margin + 90, y);

      // Footer
      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`NDIS Incident Report · ${profile?.business_name || "Provider"} · Page ${i} of ${pageCount}`, pageWidth / 2, 290, { align: "center" });
        doc.text("Generated by SoloCare · solocare.com.au", pageWidth / 2, 295, { align: "center" });
      }

      doc.save(`Incident_Report_${incident.participant_first_name}_${incident.incident_date}.pdf`);
      toast.success("PDF downloaded!");
    } catch (err) {
      toast.error("Failed to generate PDF");
      console.error(err);
    }
  }

  return (
    <Button variant="outline" size="sm" onClick={handleDownload}>
      <Download className="h-4 w-4" />
      <span className="hidden sm:inline">Download PDF</span>
    </Button>
  );
}
