import Link from "next/link";
import Image from "next/image";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — SoloCare",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#F8FAFC]">
      <header className="border-b border-slate-100 bg-white">
        <div className="max-w-3xl mx-auto px-4 h-14 flex items-center justify-between">
          <Link href="/">
            <Image src="/solocare_lockup.svg" alt="SoloCare" width={140} height={46} className="h-8 w-auto" />
          </Link>
          <Link href="/login" className="text-sm text-slate-500 hover:text-slate-700">Sign in</Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-[#0F172A] font-heading mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-400 mb-10">Last updated: March 2026</p>

        <div className="prose prose-slate max-w-none space-y-8 text-sm leading-relaxed text-slate-600">

          <section>
            <h2 className="text-base font-semibold text-[#0F172A] mb-3">1. About SoloCare</h2>
            <p>SoloCare is a compliance management tool built for Australian independent NDIS support workers. It is operated by Lumen ADL ABN [INSERT ABN], based in Adelaide, South Australia ("we", "us", "our").</p>
            <p className="mt-2">By creating an account and using SoloCare, you agree to these Terms. If you don't agree, don't use the service.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#0F172A] mb-3">2. What SoloCare does</h2>
            <p>SoloCare helps you organise compliance documents, generate policy templates, log incidents and shifts, and track your audit readiness. It is a document and workflow tool — not legal advice, and not a substitute for professional compliance consulting.</p>
            <p className="mt-2">Policy templates generated by SoloCare are produced using AI and are provided as a starting point. You are responsible for reviewing them and ensuring they meet your specific obligations under the NDIS Practice Standards.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#0F172A] mb-3">3. Your account</h2>
            <p>You must be 18 or older and operating as an NDIS support worker or provider to use SoloCare. You are responsible for keeping your login credentials secure. You must not share your account.</p>
            <p className="mt-2">You are responsible for the accuracy of the information you enter, including ABNs, participant details, and document records.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#0F172A] mb-3">4. Subscription and billing</h2>
            <p>SoloCare is a paid subscription service. Pricing is displayed on the subscribe page. Payments are processed securely by Stripe. We do not store your card details.</p>
            <p className="mt-2">Subscriptions renew automatically unless cancelled before the renewal date. You can cancel at any time from your account settings.</p>
            <p className="mt-2">We offer a 30-day money-back guarantee on your first payment. Contact us at <a href="mailto:support@solocare.com.au" className="text-[#1E3A5F] hover:underline">support@solocare.com.au</a> to request a refund within 30 days of your first charge.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#0F172A] mb-3">5. Your data</h2>
            <p>You own your data. We store it to provide the service. We do not sell it, share it with third parties for marketing, or use it to train AI models.</p>
            <p className="mt-2">If you cancel your account, you can request a copy of your data within 30 days. After 30 days, your data will be deleted from our systems.</p>
            <p className="mt-2">See our <Link href="/privacy" className="text-[#1E3A5F] hover:underline">Privacy Policy</Link> for full details.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#0F172A] mb-3">6. Participant data</h2>
            <p>You may enter information about your NDIS participants (names, NDIS numbers, plan details). You are responsible for ensuring you have the right to store and process this data, consistent with your obligations under the Australian Privacy Act 1988 and NDIS Practice Standards.</p>
            <p className="mt-2">We apply appropriate security controls to protect participant data stored in SoloCare. All data is stored in Australia.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#0F172A] mb-3">7. Acceptable use</h2>
            <p>You must not use SoloCare to store unlawful content, attempt to breach our systems, impersonate another person, or use the service in a way that could harm others.</p>
            <p className="mt-2">We reserve the right to suspend or terminate accounts that violate these terms.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#0F172A] mb-3">8. Limitation of liability</h2>
            <p>SoloCare is provided "as is". We are not liable for any compliance outcome, audit result, or NDIS Commission decision that arises from your use of the service. To the extent permitted by Australian consumer law, our liability is limited to the amount you paid in the 3 months prior to the claim.</p>
            <p className="mt-2">Nothing in these terms excludes any guarantee or right you have under the Australian Consumer Law that cannot be excluded.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#0F172A] mb-3">9. Changes to these terms</h2>
            <p>We may update these terms from time to time. We will email you at least 14 days before any material changes take effect. Continuing to use SoloCare after that date means you accept the updated terms.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-[#0F172A] mb-3">10. Contact</h2>
            <p>Questions? Email us at <a href="mailto:support@solocare.com.au" className="text-[#1E3A5F] hover:underline">support@solocare.com.au</a>.</p>
            <p className="mt-2">These terms are governed by the laws of South Australia, Australia.</p>
          </section>

        </div>
      </main>

      <footer className="border-t border-slate-100 py-8 px-4 mt-12">
        <div className="max-w-3xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3">
          <Image src="/solocare_lockup.svg" alt="SoloCare" width={100} height={33} className="h-6 w-auto" />
          <div className="flex gap-4 text-xs text-slate-400">
            <Link href="/privacy" className="hover:text-slate-600">Privacy Policy</Link>
            <Link href="/terms" className="hover:text-slate-600">Terms of Service</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
