"use client";
import { Download } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { ProgressNote } from "@/lib/types-features";
import { formatDate } from "@/lib/utils";

interface Props {
  note: ProgressNote;
  providerName: string | null;
  providerContact: string | null;
}

export function NotesPDFDownload({ note, providerName, providerContact }: Props) {
  const participantName = note.participants
    ? `${note.participants.first_name}${note.participants.last_name ? " " + note.participants.last_name : ""}`
    : "Unknown Participant";

  async function handleDownload() {
    const { default: jsPDF } = await import("jspdf");
    const doc = new jsPDF({ format: "a4", unit: "mm" });

    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;
    let y = 0;

    // Navy header bar
    doc.setFillColor(30, 58, 95);
    doc.rect(0, 0, pageWidth, 28, "F");

    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text("NDIS Progress Note", margin, 12);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`${participantName} · ${formatDate(note.session_date)}`, margin, 21);

    y = 38;

    // Session details row
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);

    const timeRange =
      note.session_start && note.session_end
        ? `${note.session_start} – ${note.session_end}`
        : note.session_start || "";
    if (timeRange) {
      doc.text(`Time: ${timeRange}`, margin, y);
    }
    if (note.support_category) {
      doc.text(`Category: ${note.support_category}`, margin + 80, y);
    }
    if (timeRange || note.support_category) y += 8;

    // Divider
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    function addSection(title: string, content: string | null) {
      if (!content) return;
      if (y + 20 > 270) { doc.addPage(); y = 20; }

      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 58, 95);
      doc.text(title, margin, y);
      y += 6;

      doc.setFont("helvetica", "normal");
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(10);

      const lines = doc.splitTextToSize(content, maxWidth);
      lines.forEach((line: string) => {
        if (y + 6 > 270) { doc.addPage(); y = 20; }
        doc.text(line, margin, y);
        y += 5.5;
      });
      y += 5;
    }

    addSection("What Happened", note.what_happened);
    addSection("Goals Worked Toward", note.goals_worked);
    addSection("Participant Response", note.participant_response);
    addSection("Follow-Up Required", note.follow_up);

    // Provider details
    if (y + 25 > 270) { doc.addPage(); y = 20; }
    y += 5;
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);
    if (providerName) {
      doc.text(`Provider: ${providerName}`, margin, y);
      y += 5;
    }
    if (providerContact) {
      doc.text(`Contact: ${providerContact}`, margin, y);
      y += 5;
    }

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(
        "Generated by SoloCare · solocare.au",
        pageWidth / 2,
        290,
        { align: "center" }
      );
    }

    const filename = `Progress_Note_${participantName.replace(/\s+/g, "_")}_${note.session_date}.pdf`;
    doc.save(filename);
    toast.success("PDF downloaded!");
  }

  return (
    <Button variant="outline" size="sm" onClick={handleDownload}>
      <Download className="h-4 w-4" />
      Download PDF
    </Button>
  );
}
